[tool.ruff]
# — General —
target-version = "py311"
line-length    = 110

# — What to lint —
# Skip the un‑maintained legacy helpers & the auto‑generated test data.
extend-exclude = [
    "legacy",
    "tests",          # unit tests already run via pytest; no need to lint them
]

# — Lint behaviour —
[tool.ruff.lint]
extend-ignore = [
    "F401",  # unused import
    "F841",  # unused variable
    "E402",  # import not at top of file (common in CLI scripts)
    "E401",  # multiple imports on one line
    "E731",  # lambda assignment
    "E701",  # multiple statements on one line
    "E741",  # ambiguous variable name like l, O, I
    "F821",  # undefined name (most come from optional deps in legacy code)
    "F811",  # redefinition of unused name (harmless in our CLI scripts)
]
