[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio_exporter"
version = "0.1.0"
description = "Personal trading utilities"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [{name = "Codex", email = "codex@example.com"}]
dependencies = [
    "rich",
    "prompt_toolkit",
    "pydantic-settings",
    "ib_insync",
    "yfinance",
    "pandas",
    "numpy",
]

[project.optional-dependencies]
# dev dependencies from requirements-dev.txt
# used for tests

dev = [
    "pytest",
    "pandas",
    "numpy",
    "requests",
]

[tool.setuptools.packages.find]
include = ["portfolio_exporter*"]
exclude = ["legacy*", "tests*", "utils*", "docs*", "ibkr_env*", "iv_history*"]

[project.scripts]
portfolio_playbook = "main:main"
