name: Sanity — trades_report --excel

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  excel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package + deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install openpyxl jq
      - name: Run sanity script
        run: ./scripts/sanity_trades_report_excel.sh

